version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: db_reservas
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: reservas_node
    ports:
      - "5432:5432"
