version: "3.8"
services:
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reservas_node"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:15
    container_name: db_reservas
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: reservas_node
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: app_reservas
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@postgres:5432/reservas_node
    depends_on:
      postgres:
        condition: service_healthy
