name: CI - API de Reservas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user_teste
          POSTGRES_PASSWORD: senha_teste
          POSTGRES_DB: banco_teste
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Gerar o Prisma Client
        run: npx prisma generate

      - name: Sincronizar o schema do Prisma com o banco
        env:
          DATABASE_URL: "postgresql://user_teste:senha_teste@localhost:5432/banco_teste?schema=public"
        run: npx prisma db push

      - name: Executar os testes (Unitários e de Integração)
        env:
          DATABASE_URL: "postgresql://user_teste:senha_teste@localhost:5432/banco_teste?schema=public"
          JWT_SECRET: "a613354705aabec2da5041d76eca55352b0f4fae6f8afc368d37a0cd63a31e3d"
          JWT_REFRESH_SECRET: "refresh_secret_teste_ci_123" # <--- ADICIONADO
        run: npm test
